version: '3.8'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "433:433"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
